/** Data model for the Five-Layer Enterprise AI Framework section on /recruiter.
 *  Presentation lives in components/ui/FiveLayerFramework.tsx — adding a layer
 *  or concept means editing this file only. */
export const fiveLayer = {
    eyebrow: "Methodology",
    title: "The Five-Layer Enterprise AI Framework",
    lead:
      "How I sequence an enterprise AI engagement. Each layer bears load for every layer that follows it — skipping one does not save time, it relocates the cost to a more expensive point later. Notice what is missing from the top of the list: technology.",
    openLabel: "Open full screen",
    src: "/five-layer-framework.html",
    iframeTitle: "The Five-Layer Enterprise AI Framework — interactive",
    layers: [
      {
        n: 1,
        name: "Business Outcome",
        question: "What business problem are we trying to solve?",
        rung: "Emerging",
        why: "Before discussing AI, understand how the organization creates value, where value is leaking, what frustrates customers, what slows employees down, how leadership defines success, and what happens if nothing changes. Without those answers it is impossible to know whether AI is even the right solution.",
        pull: "The best AI strategy doesn’t begin with AI. It begins with the business.",
        subs: [
          { label: "Value flow", detail: "How work actually moves through the organization — the real path, not the org chart. Surfaces manual handoffs, rework loops, and informal workarounds." },
          { label: "Customer friction", detail: "Where customers experience the most friction. Anchors the conversation in outcome rather than internal convenience." },
          { label: "Expertise concentration", detail: "Which decisions require your most experienced people. Finds knowledge living inside a handful of heads — the biggest opportunity and the biggest organizational risk." },
          { label: "Time loss", detail: "Where teams lose the most time. Finds repetitive work consuming highly skilled employees." },
          { label: "The forcing question", detail: "If you could solve only one problem this year, what would create the biggest business impact? Everything before produces a list; this produces a priority." },
        ],
        fails: "The problem is stated in technology terms. “We need an agent” is not a business outcome.",
        principle: "Business Before Technology",
      },
      {
        n: 2,
        name: "Governance",
        question: "What constraints, and who owns the decisions?",
        rung: "Seed",
        why: "Governance decisions are architectural constraints. What data may be used, what requires a human, what must be explainable, what must be logged — these determine the design. Discovering them after the architecture exists means rebuilding it.",
        pull: "Governance isn’t bureaucracy. It’s what allows organizations to deploy AI with confidence instead of hesitation.",
        subs: [
          { label: "Decision rights", detail: "Who approves, who halts, who is accountable. Halt authority is broad and never vetoable — an unnecessary halt is cheap, a delayed one is not." },
          { label: "Risk tiering", detail: "Governance intensity scales with consequence. Uniform rigor produces either over-governance or quiet non-compliance." },
          { label: "Human oversight", detail: "Where human judgment belongs, architecturally. Badly designed oversight is worse than none — it produces documented assurance and zero control." },
          { label: "Controls", detail: "Mapped to risk category, layer, and tier. An untested control has unknown effectiveness, which should be treated as zero." },
          { label: "Standards", detail: "NIST AI RMF · ISO/IEC 42001 · EU AI Act · OWASP LLM Top 10 · SR 11-7. Complementary, not substitutable." },
        ],
        fails: "Run as a launch gate rather than a design input. Run last, governance can only say no.",
        principle: "Governance Before Automation",
      },
      {
        n: 3,
        name: "Architecture",
        question: "What structure supports the business within the constraints?",
        rung: "Seed",
        tech: true,
        why: "Only now does technology enter. When the business problem is understood and the constraints are known, technology choices become implementation decisions instead of philosophical debates — the framework-versus-framework argument evaporates once everyone agrees what the system is for.",
        pull: "The architecture should support the business — not dictate it. Technology lives inside the framework. It doesn’t define the framework.",
        subs: [
          { label: "Models · Frameworks", detail: "Selected against known constraints, behind an abstraction layer. The model can change underneath you." },
          { label: "Knowledge bases · Retrieval", detail: "In a RAG system, retrieval quality determines system quality. Most reported generation failures are retrieval failures." },
          { label: "Integrations · Orchestration", detail: "Systems fail at the seams — context assembly, tool invocation, handoffs — not at the model." },
          { label: "Pattern escalation", detail: "Assisted generation → RAG → tool-using agent → multi-agent. Each step raises capability and governance burden together. Choose the least capable pattern that solves the problem." },
          { label: "Cross-cutting decisions", detail: "Decision logging, evaluation hooks, trace propagation, output validation, tool permissions, cost attribution. Cheap now, impossible later." },
        ],
        fails: "Chosen before Layers 1 and 2 are settled — then it is a technology preference wearing an architecture diagram.",
        principle: "Technology-Agnostic Architecture",
      },
      {
        n: 4,
        name: "Operations",
        question: "Can leadership trust this system six months from now?",
        rung: "Seed",
        why: "An AI system can be fully available, fast, error-free, and completely wrong — and nothing in a conventional monitoring stack notices. Evaluation, security, and observability are not separate stages. They are the disciplines that make this layer possible.",
        pull: "Deployment isn’t the finish line. It’s the starting line. Without operational visibility, an AI system doesn’t become an enterprise capability — it becomes an experiment.",
        subs: [
          { label: "Observability", detail: "Infrastructure, behavioral, decision trace, cost. The behavioral layer is what distinguishes AI observability, and it must be designed in." },
          { label: "Evaluation", detail: "Component, system, behavioral, adversarial, disaggregated — evaluated separately, because combined evaluation tells you it broke, not where." },
          { label: "Security", detail: "The threat model in operation. Model output treated as untrusted input; tool permissions least-privilege." },
          { label: "Incident response", detail: "Detect, halt, bound, investigate, remediate, notify, learn." },
          { label: "Ownership", detail: "A named system owner accountable through the full lifecycle — the role most commonly missing after launch." },
        ],
        fails: "Treated as post-launch overhead. Observability in particular is architectural and cannot be retrofitted.",
        principle: "Trust Before Scale",
      },
      {
        n: 5,
        name: "Continuous Improvement",
        question: "How does this evolve without getting worse?",
        rung: "Seed",
        why: "Enterprise AI is never finished. Businesses evolve, customers evolve, regulations evolve. The mechanisms that let a system evolve with them are built in from the beginning — not added after something goes wrong.",
        pull: "The organizations that succeed with AI won’t necessarily build the smartest systems first. They’ll build the systems that improve continuously.",
        subs: [
          { label: "Evaluation", detail: "Continuous, not point-in-time. Catches quality drift and regression against a maintained baseline." },
          { label: "Governance reviews", detail: "Re-assessment on a defined cadence. Catches a changed risk profile or changed regulation." },
          { label: "User feedback", detail: "Routed to someone who can act. Catches what the metrics do not show." },
          { label: "Red teaming", detail: "Recurring, not a pre-launch exercise. Catches new attack surface as the system changes." },
          { label: "Optimization", detail: "Cost and latency drift, measured against unit economics modeled at production volume." },
        ],
        fails: "There is no regression baseline, so improvement and degradation are indistinguishable.",
        principle: "Continuous Improvement",
      },
    ],
  } as const;
